

services:

  nginx:
    build:
      context: .
      dockerfile: conf/Dockerfile-nginx
    ports:
      - "8000:80"
    env_file:
      - ./env
    volumes:
      # Custom config
      - ./conf/nginx.conf.template:/etc/nginx/nginx.conf.template:ro

  httpbin:
    image: dmuth1/fastapi-httpbin
    ports:
      - "8001:80"

  tools:
    build:
      context: .
      dockerfile: conf/Dockerfile-tools

