

services:

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      # Custom config
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Our docroot
      #- ./html:/usr/share/nginx/html:ro

  httpbin:
    image: dmuth1/fastapi-httpbin
    ports:
      - "8001:80"

  tools:
    build:
      context: .
      dockerfile: Dockerfile-tools

