
FROM nginx:latest

RUN apt-get update && apt-get install -y gettext-base

CMD envsubst '${NGINX_RATE_PER_SEC} ${NGINX_BURST} ${NGINX_DELAY} ' \
  < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf \
  && nginx -g 'daemon off;'



